### ISSUE TITLE
Explore alt method

### ISSUE THREAD

**Issue by sambacha** [sambacha/workflows-cache-submodules#1]
it could be as simple as:

```yaml
name: cache
on:
  pull_request:


jobs:
  cache:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04 # x86_64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 50

    steps:
      - name: Cache configure
        id: setup-cache
        run: | # shell
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4.1.7
        with:
          repository: ''

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.repo }}-${{ github.sha }}-${{ matrix.runner }}'
          path: '${{ steps.get-meta.outputs.cache_dir }}/'
          if-no-files-found: 'error'
```

basically, 

```yaml
      - name: Cache configure
        id: setup-cache
        run: | # shell
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"
```
